### ISSUE TITLE
Manipulate XML as DOM

### ISSUE THREAD

**Issue by rmzelle** [rmzelle/style-formatter#1]
I haven't been able to figure out how to edit the XML put into the textarea box as a DOM, e.g. with http://nbubna.github.io/HTML/

I guess I can use DOMParser (https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) to turn the string into a DOM document? But how would I then invoke the HTML(.js) library on this DOM document?

@adam3smith, @fbennett, any ideas?

**Comment by rmzelle** [comment]
@adam3smith?

**Comment by rmzelle** [comment]
Page is live at http://rintze.zelle.me/style-formatter/, by the way.

**Comment by fbennett** [comment]
Not sure I understand the aim, but here goes. To put the code representing a portion of the DOM into a textarea, you would need to serialize it, since textarea only grokes strings. If you want to instantiate serialized code (like a CSL style) and then manipulate its DOM instantiation programmatically browser-side, you could use native DOM methods<strike>, or jQuery, or HTML.js -- as far as I can tell, HTML.js is a helper library meant to be used in JavaScript code. It doesn't seem to be a full-blown widget with a UI (but I could be missing something)</strike>.

**Comment by rmzelle** [comment]
@fbennett, do you have any code lying around that does something like that?

**Comment by fbennett** [comment]
Do you want to show the XML and the output it produces? (I'm not sure what should be showing / is desired in the two textarea regions of the draft page.)

**Comment by rmzelle** [comment]
Yes. I want to parse the XML from the input textarea box, edit it as a DOM
document, reindent and escape it, and show the result in the output
textarea box.

**Comment by fbennett** [comment]
So the editing will be programmatic after the XML code is pasted in -- applying some operations to the DOM, without manual intervention, and then showing the re-serialized XML code in the other box?

**Comment by fbennett** [comment]
It looks like this might be the module they're using to produce the pretty-printed output: https://github.com/nbubna/HTML/blob/master/dist/HTML.stringify.js

**Comment by fbennett** [comment]
Is it important to display the result in a web page with fancy markup? If not, a simpler tool that just produces tidied-up and serialized XML as a straight string might be easier to work with. Haven't tried it, but this may be promising for that: http://www.eslinstructor.net/vkbeautify/

**Comment by fbennett** [comment]
For the programmatic manipulation itself, xpath and straight DOM methods (including cloneNode()) should get you there. The requirement to reorder attributes in the serialized output that you mentioned the other day won't be possible (reliably) with DOM tools, but that bit could be done on the serialized output using regular expressions etc without much trouble.

**Comment by rmzelle** [comment]
So this repository is to create a stand-alone tool to implement https://github.com/citation-style-language/utilities/blob/master/csl-reindenting-and-info-reordering.py in client-side JS. Once the tool works, I can repackage it for integration into the CSL validator and your CSL-m editor.

**Comment by fbennett** [comment]
Right-o, I'm with. For testing, I wouldn't worry with rendering the result into HTML markup. You can either do a replace to escape the brackets to entities, or maybe set up an iframe in the page, fed by a data url that has the serialized text of the style. Once you have a channel for displaying the result, the coding itself shouldn't be too bad.

**Comment by fbennett** [comment]
(And it would be great to add this to the Juris-M editor. I've been meaning to ask whether you would like the "Submit" button woken up on URL-submitted CSL 1.0.1 styles, with the CSL repository as the target. If your cleaning operations can be done on the file in the browser, it would make that workflow even smoother.)

**Comment by rmzelle** [comment]
So http://rintze.zelle.me/style-formatter/ already works for reindenting, using vkbeautify. I also got the substitutions of certain unicode characters to work, except for non-breaking spaces, for some weird reason.

(and I want a string as output)

**Comment by fbennett** [comment]
Hmm, so that was a non-suggestion on my part. Sorry about that. I still don't understand what HTML.js is in the mix for. You have the string in the `doFormat()` function, and the string shows up in the textarea, so I guess the sticking point is the instantiation and manipulation of the DOM? This will instantiate it:

``` javascript
function parseXML (xmlStr) {
    if (window.DOMParser) {
      var parser=new DOMParser();
      xmlDoc=parser.parseFromString(xmlStr,"text/xml");
    } else { // code for IE
      var xmlDoc=new ActiveXObject("Microsoft.XMLDOM");
      xmlDoc.async=false;
      xmlDoc.loadXML(xmlStr);
  }
  return xmlDoc
}
```

That gives you the live XML object. It has all of the native DOM methods, so you can do things like this (silly example, but you get the idea):

``` javascript
var l = xmlDoc.getElementsByTagName("link")
var first = l[0];
var parent = l[0].parentNode;
first = parent.removeChild(first);
parent.appendChild(first);
```

After things are in order (so to speak), you should be able to dump the XML as a string with [XMLSerializer](https://developer.mozilla.org/en-US/docs/XMLSerializer). Then run the string through `vkBeautify`, and it should be ready to go (apart from reordering of attributes in the string).

`HTML.js` and jQuery operate on the browser window and document&mdash;my suggestion that they would work on arbitrary XML was a red herring (well, actually it was just wrong). So maybe a better answer to your initial question would have been "you can't".

I hope I've hit the issue this time.

**Comment by rmzelle** [comment]
Thanks, that should help.

It looks like jQuery can parse strings into XML, though: http://stackoverflow.com/a/7228219/1712389. HTML.js just seemed like a friendlier API to manipulate the DOM.

**Comment by fbennett** [comment]
Ha! Didn't know jQuery could do that. Methinks I should be the one asking for advice. :-)

**Comment by rmzelle** [comment]
Thanks for the code snippet in https://github.com/rmzelle/style-formatter/issues/1#issuecomment-109419955, Frank!

Just need to figure out the No-break space escaping and the reordering of elements in cs:info, but I made some good progress. Manipulating the DOM via the native methods turned out to be much more pleasant than using JQuery.

**Comment by rmzelle** [comment]
http://rintze.zelle.me/style-formatter/ should now give comparable output to the Python script. Test e.g. cs:info reordering with https://gist.github.com/rmzelle/e3311deb8826c7d86376. Thanks Frank!

Just need to think whether we need some UI changes.

**Comment by rmzelle** [comment]
(I take additional feature requests as well)
